---
title: "Practical Machine Learning"
author: "Maulid Hussein Bwabo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prediction Assignment Writeup
```{r}
#Data variables
training.file   = './data/pml-training.csv'
test.cases.file = './data/pml-testing.csv'
training.url    = 'http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
test.cases.url  = 'http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
```

```{r}
if (!file.exists("data")){
  dir.create("data")
}
if (!file.exists("data/submission")){
  dir.create("data/submission")
}
```

```{r}
#R-Packages
IscaretInstalled = require("caret")
##install some package 
library(ggplot2)
library(lattice)
library(caret)
##Random Forest
if(!IscaretInstalled){
  install.packages("caret")
  library("caret")
}

IsrandomForestInstalled <- require("randomForest")
##Rpart package 
if(!IsrandomForestInstalled){
  install.packages("randomForest")
  library("randomForest")
}

IsRpartInstalled <- require("rpart")
##rplot package 
if(!IsRpartInstalled){
  install.packages("rpart")
  library("rpart")
}

IsRpartPlotInstalled <- require("rpart.plot")
##set seed 
if(!IsRpartPlotInstalled){
  install.packages("rpart.plot")
  library("rpart.plot")
}

# Set seed for reproducability
set.seed(9999)
```

```{r}
download.file(training.url, training.file)
download.file(test.cases.url,test.cases.file )
```

```{r}
training   <-read.csv(training.file, na.strings=c("NA","#DIV/0!", ""))
testing <-read.csv(test.cases.file , na.strings=c("NA", "#DIV/0!", ""))
training<-training[,colSums(is.na(training)) == 0]
testing <-testing[,colSums(is.na(testing)) == 0]
```

```{r}
training <-training[,-c(1:7)]
testing <-testing[,-c(1:7)]
```

```{r}
subSamples <- createDataPartition(y=training$classe, p=0.75, list=FALSE)
subTraining <- training[subSamples, ] 
subTesting <- training[-subSamples, ]
str(subTraining)
str(subTesting)
subTesting$classe=as.factor(subTesting$classe)
str(subTesting)
head(subTraining)
View(subTraining)
subTraining$classe=as.factor(subTraining$classe)
str(subTraining)
```

```{r}
# Fit model
modFitDT <- rpart(classe ~ ., data=subTraining, method="class")
# Perform prediction
predictDT <- predict(modFitDT, subTesting, type = "class")
```

```{r}
# Plot result
rpart.plot(modFitDT, main="Classification Tree", extra=102, under=TRUE, faclen=0)
```

```{r}
##Confusion Matrix 
confusionMatrix(predictDT, subTesting$classe)
```

```{r}
##Random Forest
# Fit model
modFitRF <- randomForest(classe ~ ., data=subTraining, method="class")
# Perform prediction
predictRF <- predict(modFitRF, subTesting, type = "class")
confusionMatrix(predictRF, subTesting$classe)
```
